### ISSUE TITLE
Cure for "Too many messages in-flight" ?

### ISSUE THREAD

**Issue by utpalt** [rightscale/wstunnel#11]
** Moving from vscale to wstunnel issue grp ** 

For any appliance (or wstuncli) that remains down for any length of time, the periodic requests from gateway will fill up the queue and you'd see message like this in response to any operation you perform on RS dash.. This includes editing info about the cloud (e.g: endpointURL, creds, token etc).

What is the timeout value for the messages in the tunnel queue? What happens to the messages if the appliance comes alive? Do I really want those operations to go thru at that point or would it surprise me? Do we have a back off algo in place to reduce the frequency of requests on a supposedly dead appliance?

**Comment by tve** [comment]
Implemented response indicating that the tunnel has not been active for N minutes
