### ISSUE TITLE
Can we come up with a "health-check" method for wstunnel client?

### ISSUE THREAD

**Issue by dcjohnson76** [rightscale/wstunnel#14]
When in client mode, there's no way to get stats, or perform a health check.   @tve suggested a status file, which we can be consumed via collectd.

Ideas for stats:

1> Status of websocket connection (OK or DISCONNECTED)
2> Host of last connection
3> Response code of last server connection
4> Time stamp of last local server connection

Example:
Websocket: OK
Last Success: 10.1.2.3, 200, Mon May 11 22:25:58 UTC 2015
Last Error: 10.1.2.3, 500, Mon May 11 22:26:22 UTC 2015

**Comment by tve** [comment]
Implemented in 1.0.5
