### ISSUE TITLE
Timeouts and long requests

### ISSUE THREAD

**Issue by artembokhan** [rightscale/wstunnel#40]
Hi!

I'm trying to get working "curl <> ws-srv <> ws-cli <> nginx" configuration. I'm using curl to upload files to nginx using PUT method.

What I see is the request time limit (ws-srv <> ws-cli) is hardcoded to about 60 seconds. The uploads which last longer are failing.

Could you please add this timeout to options or give a hint where to fix it in the code?

The version from master is used.

Thanks.

**Comment by rshade** [comment]
Did you try setting either of these? https://github.com/rightscale/wstunnel/blob/master/tunnel/wstunsrv.go#L130

**Comment by rshade** [comment]
Closing as this issue has been answered over 1 year.
